import NormalizedMatches from '../src/type/normalize/matches';
import NormalizedResults from '../src/type/normalize/results';
import Statisticer from '../src/statisticer/statisticer';

const nmatches: NormalizedMatches = {
  意甲: {
    AC米蘭: [
      {
        league: '意甲',
        time: '2021-03-15',
        host: 'AC米蘭',
        away: '拿玻里',
        full: '0-1',
        half: '0-0',
        handicap: '輸[0]',
        hilo: '小[2.5]',
        oddeven: '單',
      },
      {
        league: '意甲',
        time: '2021-03-07',
        host: '維羅納',
        away: 'AC米蘭',
        full: '0-2',
        half: '0-1',
        handicap: '贏[0]',
        hilo: '小[2.5]',
        oddeven: '雙',
      },
      {
        league: '意甲',
        time: '2021-03-04',
        host: 'AC米蘭',
        away: '烏甸尼斯',
        full: '1-1',
        half: '0-0',
        handicap: '輸[-0.5/1]',
        hilo: '小[2/2.5]',
        oddeven: '雙',
      },
      {
        league: '意甲',
        time: '2021-03-01',
        host: '羅馬',
        away: 'AC米蘭',
        full: '1-2',
        half: '0-1',
        handicap: '贏[+0/0.5]',
        hilo: '走[3]',
        oddeven: '單',
      },
      {
        league: '意甲',
        time: '2021-02-21',
        host: 'AC米蘭',
        away: '國際米蘭',
        full: '0-3',
        half: '0-1',
        handicap: '輸[+0.5]',
        hilo: '大[2.5/3]',
        oddeven: '單',
      },
      {
        league: '意甲',
        time: '2021-02-14',
        host: '史柏斯亞',
        away: 'AC米蘭',
        full: '2-0',
        half: '0-0',
        handicap: '輸[-1]',
        hilo: '小[3]',
        oddeven: '雙',
      },
      {
        league: '意甲',
        time: '2021-02-07',
        host: 'AC米蘭',
        away: '克羅托內',
        full: '4-0',
        half: '1-0',
        handicap: '贏[-2]',
        hilo: '大[3]',
        oddeven: '雙',
      },
      {
        league: '意甲',
        time: '2021-01-30',
        host: '博洛尼亞',
        away: 'AC米蘭',
        full: '1-2',
        half: '0-1',
        handicap: '贏[-0.5]',
        hilo: '大[2.5/3]',
        oddeven: '單',
      },
      {
        league: '意甲',
        time: '2021-01-24',
        host: 'AC米蘭',
        away: '阿特蘭大',
        full: '0-3',
        half: '0-1',
        handicap: '輸[+0/0.5]',
        hilo: '大[2.5/3]',
        oddeven: '單',
      },
      {
        league: '意甲',
        time: '2021-01-19',
        host: '卡利亞里',
        away: 'AC米蘭',
        full: '0-2',
        half: '0-1',
        handicap: '贏[-0.5/1]',
        hilo: '小[2.5/3]',
        oddeven: '雙',
      },
      {
        league: '意甲',
        time: '2021-01-10',
        host: 'AC米蘭',
        away: '拖連奴',
        full: '2-0',
        half: '2-0',
        handicap: '贏[-0.5/1]',
        hilo: '小[2.5]',
        oddeven: '雙',
      },
      {
        league: '意甲',
        time: '2021-01-07',
        host: 'AC米蘭',
        away: '祖雲達斯',
        full: '1-3',
        half: '1-1',
        handicap: '輸[+0/0.5]',
        hilo: '大[2.5]',
        oddeven: '雙',
      },
      {
        league: '意甲',
        time: '2021-01-04',
        host: '賓尼雲圖',
        away: 'AC米蘭',
        full: '0-2',
        half: '0-1',
        handicap: '贏[-0.5/1]',
        hilo: '小[2.5/3]',
        oddeven: '雙',
      },
      {
        league: '意甲',
        time: '2020-12-24',
        host: 'AC米蘭',
        away: '拉素',
        full: '3-2',
        half: '2-1',
        handicap: '贏[-0/0.5]',
        hilo: '大[2.5/3]',
        oddeven: '單',
      },
      {
        league: '意甲',
        time: '2020-12-20',
        host: '莎索羅',
        away: 'AC米蘭',
        full: '1-2',
        half: '0-2',
        handicap: '贏[-0.5/1]',
        hilo: '走[3]',
        oddeven: '單',
      },
      {
        league: '意甲',
        time: '2020-12-17',
        host: '熱拿亞',
        away: 'AC米蘭',
        full: '2-2',
        half: '0-0',
        handicap: '輸[-1]',
        hilo: '大[2.5/3]',
        oddeven: '雙',
      },
      {
        league: '意甲',
        time: '2020-12-14',
        host: 'AC米蘭',
        away: '帕爾馬',
        full: '2-2',
        half: '0-1',
        handicap: '輸[-1.5]',
        hilo: '大[3]',
        oddeven: '雙',
      },
      {
        league: '意甲',
        time: '2020-12-07',
        host: '森多利亞',
        away: 'AC米蘭',
        full: '1-2',
        half: '0-1',
        handicap: '贏[-0.5/1]',
        hilo: '大[2.5/3]',
        oddeven: '單',
      },
      {
        league: '意甲',
        time: '2020-11-29',
        host: 'AC米蘭',
        away: '費倫天拿',
        full: '2-0',
        half: '2-0',
        handicap: '贏[-0.5/1]',
        hilo: '小[2.5/3]',
        oddeven: '雙',
      },
      {
        league: '意甲',
        time: '2020-11-23',
        host: '拿玻里',
        away: 'AC米蘭',
        full: '1-3',
        half: '0-1',
        handicap: '贏[+0/0.5]',
        hilo: '大[2.5]',
        oddeven: '雙',
      },
      {
        league: '意甲',
        time: '2020-11-09',
        host: 'AC米蘭',
        away: '維羅納',
        full: '2-2',
        half: '1-2',
        handicap: '輸[-1.5]',
        hilo: '大[3/3.5]',
        oddeven: '雙',
      },
      {
        league: '意甲',
        time: '2020-11-01',
        host: '烏甸尼斯',
        away: 'AC米蘭',
        full: '1-2',
        half: '0-1',
        handicap: '贏[-0.5]',
        hilo: '大[2.5]',
        oddeven: '單',
      },
      {
        league: '意甲',
        time: '2020-10-27',
        host: 'AC米蘭',
        away: '羅馬',
        full: '3-3',
        half: '1-1',
        handicap: '輸[-0/0.5]',
        hilo: '大[3/3.5]',
        oddeven: '雙',
      },
      {
        league: '意甲',
        time: '2020-10-18',
        host: '國際米蘭',
        away: 'AC米蘭',
        full: '1-2',
        half: '1-2',
        handicap: '贏[+0.5]',
        hilo: '走[3]',
        oddeven: '單',
      },
      {
        league: '意甲',
        time: '2020-10-05',
        host: 'AC米蘭',
        away: '史柏斯亞',
        full: '3-0',
        half: '0-0',
        handicap: '贏[-1/1.5]',
        hilo: '大[2.5/3]',
        oddeven: '單',
      },
      {
        league: '意甲',
        time: '2020-09-28',
        host: '克羅托內',
        away: 'AC米蘭',
        full: '0-2',
        half: '0-1',
        handicap: '贏[-1]',
        hilo: '小[2.5]',
        oddeven: '雙',
      },
      {
        league: '意甲',
        time: '2020-09-22',
        host: 'AC米蘭',
        away: '博洛尼亞',
        full: '2-0',
        half: '1-0',
        handicap: '贏[-1/1.5]',
        hilo: '小[3]',
        oddeven: '雙',
      },
    ],
  },
};

describe('test get handicap result', () => {
  it('cal all matches', () => {
    const expected: NormalizedResults = {
      意甲: {
        AC米蘭: {
          league: '意甲',
          team: 'AC米蘭',
          win: 17,
          draw: 0,
          lose: 10,
        },
      },
    };
    const actual: NormalizedResults = Statisticer.getHandicapRes(nmatches);
    expect(actual).toEqual(expected);
  });
});

describe('test get hilo result', () => {
  it('cal all matches', () => {
    const expected: NormalizedResults = {
      意甲: {
        AC米蘭: {
          league: '意甲',
          team: 'AC米蘭',
          win: 14,
          draw: 3,
          lose: 10,
        },
      },
    };
    const actual: NormalizedResults = Statisticer.getHiLoRes(nmatches);
    expect(actual).toEqual(expected);
  });
});
